# app/config/routing.ymlbook_index:
routers:
    
              book\/?: book/list
             
              admin\/book\/list\?page=([\d]+): admin/book/list/up/1?page=$1
             
              book\/([\d]+)\/?: book/view/$1
             
              book\/view\/([\d]+)\/?: book/view/$1
             
              book\/add\/([\d]+): book/addCart/$1
             
              contact\/?([\w]+)?\/?: contact/send
             
              security\/login: security/login
              
              security\/logout: security/logout
             
              admin\/?([\w]+)?\/?: admin/
             